//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bus_timetables
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Direction> Directions { get; set; }
        public virtual DbSet<Line> Lines { get; set; }
        public virtual DbSet<Route> Routes { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<Stop> Stops { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<FavLine> FavLines { get; set; }
        public virtual DbSet<FavRoute> FavRoutes { get; set; }
        public virtual DbSet<RouteStop> RouteStops { get; set; }
    }
}
