//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bus_timetables
{
    using System;
    using System.Collections.Generic;
    
    public partial class FavLine
    {
        public int userID { get; set; }
        public int LineID { get; set; }
        public string FavName { get; set; }
    
        public virtual Line Line { get; set; }
        public virtual User User { get; set; }
    }
}
